(!definitely-latex)
(!default-title "A Brief Tour of DrScheme version 209")
(!using-chapters)
(!toc-page 1)
(!using-chapters)
(!toc-entry 0 "1" 2 "node_chap_1" "{An Invitation to Scheme}")
(!using-chapters)
(!toc-entry 0 "2" 3 "node_chap_2" "{Interactive Environment}")
(!using-chapters)
(!toc-entry 0 "3" 4 "node_chap_3" "{Language Levels}")
(!using-chapters)
(!toc-entry 0 "4" 5 "node_chap_4" "{Images as Values}")
(!using-chapters)
(!toc-entry 0 "5" 6 "node_chap_5" "{Specifying and Displaying Numbers}")
(!using-chapters)
(!toc-entry 0 "6" 7 "node_chap_6" "{Teachpacks}")
(!using-chapters)
(!toc-entry 0 "7" 8 "node_chap_7" "{Run-Time Error Reporting}")
(!using-chapters)
(!toc-entry 0 "8" 9 "node_chap_8" "{The Stepper}")
(!using-chapters)
(!toc-entry 0 "9" 10 "node_chap_9" "{Testing}")
(!using-chapters)
(!toc-entry 0 "10" 11 "node_chap_10" "{The Profiler}")
(!using-chapters)
(!toc-entry 0 "11" 12 "node_chap_11" "{Program Browsing}")
(!using-chapters)
(!toc-entry 0 "12" 13 "node_chap_12" "{XML Boxes}")
(!using-chapters)
(!toc-entry 0 "13" 14 "node_chap_13" "{Printing Values}")
(!using-chapters)
(!toc-entry 0 "14" 15 "node_chap_14" "{Portability}")
(!using-chapters)
(!toc-entry 0 "15" 16 "node_chap_15" "{Conclusion}")
(!last-page-number 16)
(!last-modification-time 1103440234)
